# Generated by Django 5.2.12 on 2026-04-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_phone_booking_phone_number_alter_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='materials',
            field=models.JSONField(),
        ),
    ]
